"""Add vision board tables

Revision ID: 27786d03a42b
Revises: 3f88148c123d
Create Date: 2025-12-28 18:05:44.183085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27786d03a42b'
down_revision: Union[str, Sequence[str], None] = '3f88148c123d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_goals_id'), 'vision_goals', ['id'], unique=False)
    op.create_table('vision_subgoals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('vision_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vision_goal_id'], ['vision_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_subgoals_id'), 'vision_subgoals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_subgoals_id'), table_name='vision_subgoals')
    op.drop_table('vision_subgoals')
    op.drop_index(op.f('ix_vision_goals_id'), table_name='vision_goals')
    op.drop_table('vision_goals')
    # ### end Alembic commands ###
